add_newline = false


[directory]
truncation_length = 2
style = "bright-blue"
format = "[$path ]($style)[$read_only]($read_only_style)"

[username]
style_user = "white bold"
style_root = "black bold"
format = "[$user]($style) "
disabled = true
show_always = true

[hostname]
ssh_only = false
format =  "[$hostname](bold red) "
disabled = false

[character]    
success_symbol = "[➜](bold green) "
error_symbol = "[✗](bold red) "
